# Generated by Django 4.0.4 on 2023-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('information', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'login',
                'managed': True,
            },
        ),
    ]
