# Generated by Django 4.0.4 on 2023-01-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
