# Generated by Django 4.0.4 on 2023-01-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
