# Generated by Django 4.0.4 on 2023-01-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=200)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
    ]
