# Generated by Django 4.0.4 on 2023-01-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='questionnum',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
