# Generated by Django 4.0.4 on 2023-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_homework_questionnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('questiontype', models.CharField(max_length=255)),
                ('questionnum', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questionbank',
                'managed': True,
            },
        ),
    ]
