# Generated by Django 4.0.4 on 2023-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ansid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('questionid', models.CharField(max_length=255)),
                ('question', models.TextField(max_length=10000)),
                ('answer', models.TextField(max_length=10000)),
                ('questiontype', models.CharField(max_length=255)),
                ('highsimilarity', models.CharField(max_length=255)),
                ('questionnum', models.CharField(max_length=255)),
                ('homeworkid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
