# Generated by Django 4.0.4 on 2023-02-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_answer_options_alter_answer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='optionA',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='optionB',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='optionC',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='optionD',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
