# Generated by Django 4.0.4 on 2023-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_questionbank_optiona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='highsimilarity',
            new_name='highsimilarityA',
        ),
        migrations.AddField(
            model_name='answer',
            name='highsimilarityB',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='highsimilarityC',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
