# Generated by Django 4.0.4 on 2023-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename_highsimilarity_answer_highsimilaritya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selecttype',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
