# Generated by Django 4.0.4 on 2023-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_answer_selecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='highsimilarityA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='highsimilarityB',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='highsimilarityC',
            field=models.FloatField(default=0.0),
        ),
    ]
