# Generated by Django 4.0.4 on 2023-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_answer_highsimilaritya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joincourse',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('courseid', models.CharField(max_length=255)),
                ('coursename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'joincourse',
                'managed': True,
            },
        ),
    ]
