# Generated by Django 4.0.4 on 2023-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_joincourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincourse',
            name='classname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
