# Generated by Django 4.0.4 on 2023-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_joincourse_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestSimilarityA',
            fields=[
                ('said', models.AutoField(primary_key=True, serialize=False)),
                ('userida', models.CharField(max_length=255)),
                ('useridb', models.CharField(max_length=255)),
                ('ansid', models.CharField(max_length=255)),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'highestsimilaritya',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HighestSimilarityB',
            fields=[
                ('sbid', models.AutoField(primary_key=True, serialize=False)),
                ('userida', models.CharField(max_length=255)),
                ('useridb', models.CharField(max_length=255)),
                ('ansid', models.CharField(max_length=255)),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'highestsimilarityb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HighestSimilarityC',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('userida', models.CharField(max_length=255)),
                ('useridb', models.CharField(max_length=255)),
                ('ansid', models.CharField(max_length=255)),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'highestsimilarityc',
                'managed': True,
            },
        ),
    ]
