# Generated by Django 4.0.4 on 2023-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_highestsimilaritya_highestsimilarityb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestsimilaritya',
            name='homeworkid',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='highestsimilarityb',
            name='homeworkid',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='highestsimilarityc',
            name='homeworkid',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
