# Generated by Django 4.0.4 on 2023-04-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_highestsimilaritya_homeworkid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitHomework',
            fields=[
                ('subid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('homeworkid', models.CharField(max_length=255)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('questionnum', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'submithomework',
                'managed': True,
            },
        ),
    ]
