# Generated by Django 4.0.4 on 2023-04-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_submithomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
