# Generated by Django 4.0.4 on 2023-04-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_submithomework_ctime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSimilarity',
            fields=[
                ('simid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('homeworkid', models.CharField(max_length=255)),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'homeworksimilarity',
                'managed': True,
            },
        ),
    ]
