# Generated by Django 4.0.4 on 2023-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, unique=True)),
                ('p_age', models.IntegerField(default=10)),
                ('p_sex', models.BooleanField(default=True)),
            ],
        ),
    ]
