# Generated by Django 4.0.4 on 2023-01-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
