# Generated by Django 4.0.4 on 2023-01-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
